services:
  server:
    build:
      context: .
      dockerfile: docker/server/Dockerfile
      args:
        DEPENDENCIES_TAG: ${DEPENDENCIES_TAG}
    restart: always
    environment:
      ENVIRONMENT: test
      LOG_LEVEL: debug
      DATABASE_URL: 'postgresql://tun-judge:tun-judge@db:5432/tun-judge?schema=public'
      DATABASE_DIRECT_URL: 'postgresql://tun-judge:tun-judge@db:5432/tun-judge'
      SESSION_SECRET: secret
      REDIS_URL: 'redis://redis:6379'
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis

  judge:
    build:
      context: .
      dockerfile: docker/judge/Dockerfile
      args:
        DEPENDENCIES_TAG: ${DEPENDENCIES_TAG}
    restart: always
    environment:
      ENVIRONMENT: test
      HOSTNAME: judgehost
      TUN_JUDGE_URL: http://server:3000
      TUN_JUDGE_USERNAME: judge-host
      TUN_JUDGE_PASSWORD: judge-host
    volumes:
      - /tmp/tun-judge/workDir:/tmp/tun-judge/workDir
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - server

  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_DB: tun-judge
      POSTGRES_USER: tun-judge
      POSTGRES_PASSWORD: tun-judge
    volumes:
      - /opt/tun-judge/db-data:/var/lib/postgresql/data

  redis:
    image: bitnami/redis:6.0
    restart: always
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - redis-data:/bitnami/redis/data

volumes:
  redis-data:
    driver: local
