import { ClarificationsStore } from '@core/stores/ClarificationsStore';
import { ContestsStore } from '@core/stores/ContestsStore';
import { ExecutablesStore } from '@core/stores/ExecutablesStore';
import { JudgeHostsStore } from '@core/stores/JudgeHostsStore';
import { LanguagesStore } from '@core/stores/LanguagesStore';
import { ProblemsStore } from '@core/stores/ProblemsStore';
import { PublicStore } from '@core/stores/PublicStore';
import { RootStore } from '@core/stores/RootStore';
import { SubmissionsStore } from '@core/stores/SubmissionsStore';
import { TeamCategoriesStore } from '@core/stores/TeamCategoriesStore';
import { TeamStore } from '@core/stores/TeamStore';
import { TeamsStore } from '@core/stores/TeamsStore';
import { TestcasesStore } from '@core/stores/TestcasesStore';
import { UsersStore } from '@core/stores/UsersStore';

export type Stores = {
  rootStore: RootStore;
  publicStore: PublicStore;
  teamStore: TeamStore;
  usersStore: UsersStore;
  teamsStore: TeamsStore;
  contestsStore: ContestsStore;
  problemsStore: ProblemsStore;
  testcasesStore: TestcasesStore;
  languagesStore: LanguagesStore;
  judgeHostsStore: JudgeHostsStore;
  executablesStore: ExecutablesStore;
  submissionsStore: SubmissionsStore;
  teamCategoriesStore: TeamCategoriesStore;
  clarificationsStore: ClarificationsStore;
};
