name: Build

on: push

concurrency: ${{ github.ref }}

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Install NodeJs 14
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Yarn Install
        run: yarn install

      - name: Lint
        run: yarn lint

      - name: Prettier
        run: yarn prettier

      - name: Update Version
        if: github.ref == 'refs/heads/main'
        run: |
          git config user.email "nasreddine.bacali95@gmail.com"
          git config user.name "Nasreddine Bac Ali"
          yarn release

      - name: Build Server
        run: docker build -t tunjudge/server -f docker/server/Dockerfile .

      - name: Build Judge
        run: docker build -t tunjudge/judge -f docker/judge/Dockerfile .

      - name: Run app for testing
        run: docker-compose -f docker-compose.test.yml up -d

      - name: Integration tests
        uses: cypress-io/github-action@v2
        with:
          working-directory: tests
          install: false
          browser: chrome
          record: true
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Stop app
        run: docker-compose -f docker-compose.test.yml down

      - name: Push Images
        if: github.ref == 'refs/heads/main'
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          yarn image:tag-and-push tunjudge/server
          yarn image:tag-and-push tunjudge/judge

      - name: Push Changes
        if: github.ref == 'refs/heads/main'
        run: git push
