name: Build

on:
  push:
    branches-ignore:
      - 'chore(release): *'
    tags-ignore:
      - 'v*'
  pull_request:
    tags-ignore:
      - 'v*'

concurrency: ${{ github.ref }}

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Install NodeJs 14
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Yarn Install
        run: yarn install

      - name: Lint
        run: yarn lint

      - name: Prettier
        run: yarn prettier

      - name: Build Server Docker image
        uses: docker/build-push-action@v2
        with:
          file: docker/server/Dockerfile
          tags: tun-judge/server:latest

      - name: Build Judge Docker image
        uses: docker/build-push-action@v2
        with:
          file: docker/judge/Dockerfile
          tags: tun-judge/judge:latest

      - name: Start Application
        run: docker-compose -f docker-compose.test.yml up -d

      - name: Integration tests
        uses: cypress-io/github-action@v2
        with:
          working-directory: tests
          install: false
          browser: chrome
          record: true
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Stop Application
        run: docker-compose -f docker-compose.test.yml down
